Repository pchalupa/expo-alternate-app-icons, pull requests merged in 2024-10, with the labels that each got.

#103 chore: update example project with expo sdk 51
  example/package-lock.json
  example/package.json
Labels: dependencies

#106 fix(android): jvm target version
  android/build.gradle
  example/package-lock.json
  example/package.json
Labels: bug, android, patch

#107 fix(android): handle fully qualified name for activity classes
  android/src/main/java/expo/modules/alternateappicons/ExpoAlternateAppIconsModule.kt
Labels: patch

#108 chore(example): enable new architecture
  example/app.json
  example/package-lock.json
  example/package.json
Labels: skip-release
