Repository pchalupa/expo-alternate-app-icons, pull requests merged in 2025-01, with the labels that each got.

#139 docs: add pr template
  .github/pull_request_template.md
Labels: documentation, skip-release

#138 feat: upgrade to expo 52
  example/app.json
  example/package-lock.json
  example/package.json
  package-lock.json
  package.json
  plugin/src/types.ts
  plugin/src/withAlternateAppIconsGenerator.ts
  tsconfig.json
Labels: dependencies, minor

#143 fix: ios transparency dark icons
  plugin/src/generateUniversalIcon.ts
Labels: patch
